# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:    
    - cron: "0 1 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Checkout theme jsonresume-theme-aurora
        uses: actions/checkout@v2
        with:
          repository: 'saurabh73/jsonresume-theme-aurora'
          path: 'jsonresume-theme-aurora'

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with: 
          node-version: 14.x
      
      - name: Install Resume CLI
        run: npm install -g resume-cli@3.0.0
  
      - name: Install Theme Dependencies
        run: npm install -C $GITHUB_WORKSPACE/jsonresume-theme-aurora

      - name: Build Resume
        run: resume export --format html --theme "./jsonresume-theme-aurora" index.html
        env:
          THEME_NO: 3
      
      - name: Archive Generated Resume
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: index.html
  
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Download index.html
        uses: actions/download-artifact@v2
        with:
          name: output
          
      - name: Print index.html
        run: |
          cat index.html